
# HTTP Status Codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500


# Response Messages
SUCCESS_MESSAGE = "Request was successful"
VALIDATION_ERROR_MESSAGE = "Validation error occurred"
SERVER_ERROR_MESSAGE = "Internal server error"
UNAUTHORIZED_MESSAGE = "Unauthorized access"
